### ISSUE TITLE
Suggestion: Publish changelog in repository

### ISSUE THREAD

**Issue by mbs-c** [jgrahamc/gmsl#1]
First of all, it's great to see that gmsl made it to GitHub!

I'm considering upgrading from an old version to the latest 1.2.0 version and now wondering what changed in the meantime. Since the change history is not visible in GitHub, that is pretty hard to figure out.

On SourceForge, you occasionally wrote blog posts for new versions. Would it be possible to move this information into a Changelog.md file inside the GitHub repository and add the missing descriptions for the other releases?

**Comment by jgrahamc** [comment]
This is a very good idea. I'll add a changelog.

**Comment by jgrahamc** [comment]
Done

**Comment by mbs-c** [comment]
Thank you very much!
